### ISSUE TITLE
Regression - ingest fails when library has DRM cert but no ABR Profile in metadata

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-studio#27]
error - ABR Profile has no relevant playout formats (when DRM chosen)

Possibly regression introduced by bug fix for  `abr` being undefined even though set in library metadata?

Also - need to add to test cases - test against library that has no abr/default_profile.

**Comment by elv-zenia** [comment]
Fixed by https://github.com/eluv-io/elv-studio/pull/26/files/c8fb73605c4c93e94531344880d6b34c8d7b0272..4283d7e9993ac74ce118177475c922478a756449
Changes deployed to demo.
The flows for setting an ABR profile are:
- If the library has a profile, disable options relevant based on what it doesn't support. E.g., if no clear formats, disable Clear.
- If the library has NO profile and NO DRM cert, set the profile as a default Clear profile.
- If the library has NO profile and HAS DRM cert, set the profile as a default DRM profile

**Comment by elv-gerald** [comment]
I found a bug for this case

> If the library has a profile, disable options relevant based on what it doesn't support. E.g., if no clear formats, disable Clear.

I set up a library with only hls-clear and hls-fairplay as playout formats.
```
"playout_formats": {
        "hls-clear": {
          "drm": null,
          "protocol": {
            "type": "ProtoHls"
          }
        },
        "hls-fairplay": {
          "drm": {
            "enc_scheme_name": "cbcs",
            "license_servers": [],
            "type": "DrmFairplay"
          },
          "protocol": {
            "type": "ProtoHls"
          }
        }
      },
```

In the app I noticed I had the ability to choose any playout encryption. I was expecting for only custom and clear to be selectable based on my library settings. If I chose one of the other formats, such as public access, the mez will ingest but not be playable
![image](https://user-images.githubusercontent.com/79117605/226801433-0c5a5767-7de0-4fb2-8f46-4c51e2c23e94.png)
![image](https://user-images.githubusercontent.com/79117605/226801518-d0e26c58-01e3-4452-84a1-069b425cce1a.png)

**Comment by elv-zenia** [comment]
Fixed by [b0fcc](https://github.com/eluv-io/elv-studio/pull/26/commits/b0fcc171e7303571ca3ccbe27e7ef634026e50d0) and deployed to demo.

**Comment by elv-gerald** [comment]
> Fixed by [b0fcc](https://github.com/eluv-io/elv-studio/pull/26/commits
/b0fcc171e7303571ca3ccbe27e7ef634026e50d0) and deployed to demo.

confirmed the fix is working. Using the library that only has clear and fairplay available I only see the options that fairplay or clear are a part of. I also see a relevant error if my browser cannot play any of the enabled formats and if the browser does support the format, the mez is playable. 

 
<img width="867" alt="Screenshot 2023-03-22 at 10 41 08 PM" src="https://user-images.githubusercontent.com/79117605/227116351-0cf819bf-de6f-4c9e-be3c-c276b8ba4da0.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/79117605/227116712-34caab8d-ae52-40d8-ad1d-1d3de2c8ac00.png">

**Comment by elv-gerald** [comment]
The last bug I see is I can get around the playback encryption choices. For example I can ingest with drm on a clear only library by:
1. selecting a drm enabled librar in the library dropdown. 
2. Select a drm playback encryption
3. Update the library to a clear only library

Here is a video


https://user-images.githubusercontent.com/79117605/227117452-864cf772-c0b1-4b98-940c-8bca4c642280.mov

**Comment by eponymous301** [comment]
> confirmed the fix is working. Using the library that only has clear and fairplay available I only see the options that fairplay or clear are a part of. I also see a relevant error if my browser cannot play any of the enabled formats and if the browser does support the format, the mez is playable.

Hmm, this scenario probably should only warn rather than block the user. (It's possible someone could actually be using Chrome to set up a mez that only plays HLS-Fairplay - or some other combination where the browser used for ingest won't be able to play the resulting mez)

(Am I misunderstanding? Are you still allowed to ingest?)

**Comment by elv-gerald** [comment]
Cleared the above on slack. But yes I was allowed to ingest.

**Comment by elv-zenia** [comment]
Fixed by [2db22a](https://github.com/eluv-io/elv-studio/pull/26/commits/2db22ac3fc42b42261425b879c368631f22b7182) and deployed to demo.

**Comment by elv-zenia** [comment]
Closing as completed in accordance with https://eluvio.slack.com/archives/CF7AQGUH0/p1679614038030129.
