### ISSUE TITLE
Ingest form defaults to first item on content type list

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-studio#30]
While creating an ingest if I pick a library that has `mez_content_type` defined in its metadata, the “Mezzanine Content Type” drop down defaults to the first one on the list (In this case ABR Master)

![image](https://user-images.githubusercontent.com/79117605/226753134-b31726c0-f75f-400c-a792-6d54127c553c.png)

**Comment by elv-zenia** [comment]
Fixed by https://github.com/eluv-io/elv-studio/pull/26/files/10b077ae7377ab1debb812490dc451acdb21e5b4..c69984a95c11e0a76eba242d45c25f60fced783a. Deployed to demo.
NOTE: I extended support of the mez_content_type property in the library abr. The mez content type can be an object id, version hash, or name string.

**Comment by elv-gerald** [comment]
Verfied I tested with each type as my `mez_content_type` and used a custom profile to test
